
platform :ios, '8.0'
use_frameworks!

target 'iOSDemo' do

  pod 'ReactiveCocoa'
  pod 'ReactiveViewModel'
  
  pod 'thrift', '~> 0.9.3'
  
  pod 'AFNetworking' 
  pod 'YYKit'
  pod 'NSData+Base64'
  pod 'MBProgressHUD'
  pod 'SVPullToRefresh'
  pod 'SDWebImage'
  pod 'DateTools'
  pod 'XRefresh'
  pod 'CTPersistance'
  pod 'GCDWebServer'
  pod 'GCDWebServer/WebUploader'
  pod 'GCDWebServer/WebDAV'
  pod 'RNCryptor'
  pod 'SVGAPlayer', '~> 2.3.3'
  pod 'BaiduMapKit'
  pod 'BMKLocationKit'
  pod 'Masonry'
#  pod 'XDPhoto'
  pod 'JSONModel', '~> 1.8.0'
  
  pod 'DoraemonKit/Core', :configurations => ['Debug']
  pod 'DoraemonKit/WithLogger', :configurations => ['Debug']
  pod 'DoraemonKit/WithGPS', :configurations => ['Debug']
  pod 'DoraemonKit/WithLoad', :configurations => ['Debug']
  pod 'DoraemonKit/WithWeex', :configurations => ['Debug']
  pod 'DoraemonKit/WithDatabase', :configurations => ['Debug']
  pod 'DoraemonKit/WithMLeaksFinder', :configurations => ['Debug']
  
#  Using AFNetworking (3.2.0)
#  Using CTMediator (13)
#  Using CTPersistance (169)
#  Using DateTools (2.0.0)
#  Installing GCDWebServer (3.4.2)
#  Using MBProgressHUD (1.1.0)
#  Using NSData+Base64 (1.0.0)
#  Installing RNCryptor (5.0.3)
#  Using ReactiveCocoa (2.5)
#  Using ReactiveViewModel (0.3)
#  Using SDWebImage (4.3.3)
#  Using SQLCipher (3.4.2)
#  Using SVPullToRefresh (0.4.1)
#  Using XRefresh (1.2.0)
#  Using YYKit (1.0.9)
#  Using thrift (0.9.3)
end

