#source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

platform :ios, '11.0'
use_frameworks!

target 'iOSDemo' do

  pod 'ReactiveCocoa'
  pod 'ReactiveViewModel'
  
  pod 'thrift', '~> 0.9.3'
  
  pod 'AFNetworking'
  pod 'YYKit'
  pod 'NSData+Base64'
  pod 'MBProgressHUD'
  pod 'SVPullToRefresh'
  pod 'SDWebImage'
  pod 'DateTools'
  pod 'XRefresh'
  pod 'CTPersistance'
  pod 'GCDWebServer'
  pod 'GCDWebServer/WebUploader'
  pod 'GCDWebServer/WebDAV'
  pod 'RNCryptor'
  pod 'SVGAPlayer', '~> 2.3.3'
#  pod 'BaiduMapKit'
#  pod 'BMKLocationKit'
  pod 'Masonry'
  pod 'RxSwift'
  pod 'Alamofire'
#  pod 'ijkplayer'
#  pod 'XDPhoto'
  pod 'JSONModel', '~> 1.8.0'
  pod 'CTMediator', '~> 25'
  pod 'JLRoutes', '~> 2.1'
  pod 'GPUImage', '~> 0.1.7'
  pod 'TPJsBridge', '~> 0.0.24'
  pod 'FBAllocationTracker', :configurations => ['Debug']
  pod 'FBRetainCycleDetector', :configurations => ['Debug']
  pod 'FBMemoryProfiler', :configurations => ['Debug']
#  pod 'AsyncDisplayKit'
  pod 'Texture'
  pod 'FDStackView'
#  pod 'HCMVManager', '~> 1.6.4'
  pod 'DoraemonKit/Core', :configurations => ['Debug']
  pod 'DoraemonKit/WithLogger', :configurations => ['Debug']
  pod 'DoraemonKit/WithGPS', :configurations => ['Debug']
  pod 'DoraemonKit/WithLoad', :configurations => ['Debug']
  pod 'DoraemonKit/WithWeex', :configurations => ['Debug']
  pod 'DoraemonKit/WithDatabase', :configurations => ['Debug']
  pod 'DoraemonKit/WithMLeaksFinder', :configurations => ['Debug']
  #解压压缩 zip rar 7z
  pod 'SSZipArchive'
  pod 'UnrarKit'
  pod 'LzmaSDK-ObjC'
  pod 'BookReader'
  pod 'pdftotxt'
#  pod 'SwiftOCR'
  pod 'LZUberSignature', '~> 1.0.4'
end

